/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Y9JygGNgbjn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import {useContext, useEffect, useState} from "react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Toggle } from "@/components/ui/toggle"
import {UserSelectionsContext} from "@/contexts/UserSelectionsContext";
import {fetchZkCards, fetchFwzyCards, fetchJbCards} from "@/services/api";
import {RoleContext} from "@/contexts/RoleContext";

export default function Fwzy() {
  const [isChecked, setIsChecked] = useState<any>({})
  const [list, setList] = useState<any[]>([]);

  const { userSelections, selectItem, deleteItem } = useContext(UserSelectionsContext);
  const { updateRole } = useContext(RoleContext);
  const [lock, setLock] = useState(false);

  useEffect(() => {
    let isMounted = true;
    // 只在组件挂载时运行一次
    (async () => {
      const list = await fetchFwzyCards();
      if (isMounted) {
        setList(list);
      }
    })();

    // 清理函数，确保在组件卸载前取消异步操作
    return () => {
      isMounted = false;
    };
  }, []); // 无依赖数组意味着此 effect 只在挂载时运行一次

  useEffect(() => {
    setLock(true);
    // 恢复状态
    if (userSelections.fwzySelection.length > 0) {
      userSelections.fwzySelection.map((card:any) => {
        if (userSelections.fwzySelection.some((item:any) => item.id === card.id)) {
          setIsChecked((prevState:any) => ({
            ...prevState,
            [card.id]: true,
          }))
        }
      })
    }
    setLock(false);
  }, [userSelections.fwzySelection])

  const handleCardClick = async (category:any, card:any) => {
    const id = card.id;
    if (lock) return;

    setLock(true);

    try {
      if (!userSelections.fwzySelection.some((item:any) => item.id === card.id)) {
        if (userSelections.fwzySelection.length < 10) {
          setIsChecked((prevState:any) => ({
            ...prevState,
            [id]: true,
          }));
          await selectItem(category, card);
          await updateRole(card.sx, '符文之语', 'add');
        } else {
          return;
        }
      } else {
        setIsChecked((prevState:any) => ({
          ...prevState,
          [id]: false,
        }));
        await deleteItem(category, card.id);
        await updateRole(card.sx, '符文之语', 'remove');
      }
    } finally {
      setLock(false);
    }
  };

  const [searchTerm, setSearchTerm] = useState("")
  const filteredFwzyCards = list.filter((card:any) =>
      card.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div>
      <div className="bg-background p-4 mb-6 rounded-lg shadow-lg">
        <div className="flex items-center gap-4">
          <Input
            type="search"
            placeholder="输入名称查找"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="flex-1"
          />
          <Button variant="outline">查找</Button>
        </div>
      </div>
      <div className="flex grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-8 xl:grid-cols-12 gap-6 p-4">
        {filteredFwzyCards.map((card:any) => (
          <Card
            key={card.id}
            className={`relative overflow-hidden rounded-lg shadow-lg ${
              isChecked[card.id]
                ? "border-2 golden-glow ring-4 ring-primary-foreground"
                : userSelections.fwzySelection.some((item:any) => item.id === card.id)
                ? "border-2 border-gold"
                : ""
            }`}
            onClick={() => handleCardClick('fwzySelection', card)}
          >
            <div className="relative">
              <img
                src={card.pic}
                alt={card.name}
                width={600}
                height={400}
                className="object-cover w-full h-48"
              />
            </div>
            <CardContent className="p-4 bg-background">
              <h3 className="text-xl font-bold">{card.name}</h3>
              <div className="mt-2">

              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
