/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y9JygGNgbjn
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Prata } from 'next/font/google'

 prata({
  subsets: ['latin'],
  display: 'swap',
})

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/

import {useContext, useState} from "react"
import {Input} from "@/components/ui/input"
import {Button} from "@/components/ui/button"
import {Card, CardContent} from "@/components/ui/card"
import {UserSelectionsContext} from "@/contexts/UserSelectionsContext";
import {RoleContext} from "@/contexts/RoleContext";

export default function Jb() {
    const [isChecked, setIsChecked] = useState<any>({})
    const {userSelections, selectItem, deleteItem} = useContext(UserSelectionsContext);
    const {updateRole, lists} = useContext(RoleContext);
    const list = lists.jbList;
    const handleCardClick = async (category: any, card: any) => {
        const id = card.id;
        if (!userSelections.jbSelection.some((item: any) => item.id === card.id)) {
            if (userSelections.jbSelection.map((jb: any) => jb.num).reduce(
                (a: number, b: number) => a + b,
                0
            ) + card.num <= 12) {
                selectItem(category, card);
            } else {
                return;
            }
        } else {
            deleteItem(category, card.id);
        }
    };
    const [searchTerm, setSearchTerm] = useState("")
    const filteredJbCards = list.filter((card: any) =>
        card.name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div>
            <div className="bg-background p-4 mb-6 rounded-lg shadow-lg">
                <div className="flex items-center gap-4">
                    <Input
                        type="search"
                        placeholder="输入名称查找"
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="flex-1"
                    />
                    <Button variant="outline">查找</Button>
                </div>
            </div>
            <div
                className="flex grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 gap-6 p-4">
                {filteredJbCards.map((card: any) => (
                    <Card
                        key={card.id}
                        className={`relative overflow-hidden rounded-lg shadow-lg ${
                            userSelections.jbSelection.some((item: any) => item.id === card.id)
                                ? "border-2 golden-glow ring-4 ring-primary-foreground"
                                : "border-2 border-gold"
                        }`}
                        onClick={() => handleCardClick('jbSelection', card)}
                    >
                        <div className="relative">
                            <img
                                src={card.pic}
                                alt={card.name}
                                width={600}
                                height={400}
                                className="object-cover w-full h-48"
                            />
                        </div>
                        <CardContent className="p-4 bg-background">
                            <h3 className="text-xl font-bold">{card.name}</h3>
                            <div className="mt-2">
                                {card.description}
                            </div>
                        </CardContent>
                    </Card>
                ))}
            </div>
        </div>
    )
}
