/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y9JygGNgbjn
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Prata } from 'next/font/google'

 prata({
  subsets: ['latin'],
  display: 'swap',
})

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/

import {useContext, useState} from "react"
import {Input} from "@/components/ui/input"
import {Button} from "@/components/ui/button"
import {Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle} from "@/components/ui/card"
import {UserSelectionsContext} from "@/contexts/UserSelectionsContext";
import {RoleContext} from "@/contexts/RoleContext";
import {Tabs, TabsContent, TabsList, TabsTrigger} from "@/components/ui/tabs";

export default function Tt() {
    const [activeTab, setActiveTab] = useState("active")
    const contextValue = useContext(UserSelectionsContext);
    const {updateRole, lists} = useContext(RoleContext);

    const handleCardClick = async (card: any) => {
        localStorage.setItem('userSelections', JSON.stringify(card.selections));
        window.location.reload();
    };

    const [searchTerm, setSearchTerm] = useState("");
    const [checkedCard, setCheckedCard] = useState({id: 0})
    const [cardDisplay, setCardDisplay] = useState(true)

    const filteredCards = lists.ttList.filter((card: any) =>
        card.name.toLowerCase().includes(searchTerm.toLowerCase()) || card.description.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div>
            <div className="z-10 bg-background p-4 mb-6 rounded-lg shadow-lg">
                <div className="flex items-center gap-4">
                    <Input
                        type="search"
                        placeholder="输入名称查找"
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="flex-1"
                    />
                    <Button variant="outline">查找</Button>
                    <Button variant="outline" onClick={() => setCardDisplay(!cardDisplay)}>切换显示</Button>
                </div>
            </div>
            <div
                className="flex grid grid-cols-2 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-1 gap-6 p-4">
                {filteredCards.sort((a: any, b: any) => b.totalScore - a.totalScore).map((card: any) => (
                    cardDisplay?<Card
                        key={card.id}
                        className={`relative overflow-hidden rounded-lg shadow-lg ${
                            checkedCard.id === card.id
                                ? "border-2 golden-glow ring-4 ring-primary-foreground"
                                : "border-2 border-gold"
                        }`}
                        onClick={() => setCheckedCard(card)}
                        onDoubleClick={() => handleCardClick(card)}
                    >
                            <CardContent className="p-4 bg-background">
                            <img
                                src={card.pic}
                                alt={card.name}
                                width={600}
                                height={400}
                                className="object-cover w-full h-28"
                            />
                            <h3 className="text-xl font-bold">{card.name}-{card.totalScore}</h3>
                            <div className="mt-2">
                                {card.description}
                            </div>
                        </CardContent>
                        <CardFooter>{card.author}</CardFooter>
                    </Card>:
                        <div key={card.id}>
                            <Card className={`relative overflow-hidden rounded-lg shadow-lg ${
                                    checkedCard.id === card.id
                                        ? "border-2 golden-glow ring-4 ring-primary-foreground"
                                        : "border-2 border-gold"
                                }`}
                                onClick={() => setCheckedCard(card)}
                                onDoubleClick={() => handleCardClick(card)}>
                                <CardHeader>{card.name}-{card.totalScore}-{card.author}</CardHeader>
                            </Card>
                        </div>
                ))}
            </div>
        </div>
    )
}
